three:
    path: /3
    controller: App\Controller\DefaultController::three

index:
    path: /
    controller: App\Controller\DefaultController::index
    
all:
    path: /all
    controller: App\Controller\ProductsController::showAll
    
cat:
    path: /cat
    controller: App\Controller\ProductsController::showCat    